name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [Release, Release32]
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update && sudo apt install -y cmake ninja-build
    - name: Configure
      run: cmake --preset ${{ matrix.preset }}
    - name: Build
      run: |
        cd build*
        ninja
    - uses: actions/upload-artifact@v4
      with:
       name: ${{ matrix.preset }}
       path: |
         build*/*.exe
         build*/*.pdb
         *.hlsl
